//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatMessage
    {
        public long idMessage { get; set; }
        public int idUserRoomChat { get; set; }
        public string textMessage { get; set; }
        public System.DateTime dateMessage { get; set; }
    
        public virtual userRoomChat userRoomChat { get; set; }
    }
}
