//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.categoryGame = new HashSet<categoryGame>();
            this.userGame = new HashSet<userGame>();
        }
    
        public int idGame { get; set; }
        public string nameGame { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public string logo { get; set; }
        public decimal price { get; set; }
        public Nullable<int> idAgeLimit { get; set; }
    
        public virtual ageLimit ageLimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoryGame> categoryGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userGame> userGame { get; set; }
    }
}
