//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ageLimit> ageLimit { get; set; }
        public virtual DbSet<balance> balance { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<categoryGame> categoryGame { get; set; }
        public virtual DbSet<chatMessage> chatMessage { get; set; }
        public virtual DbSet<game> game { get; set; }
        public virtual DbSet<operationBalance> operationBalance { get; set; }
        public virtual DbSet<parentControl> parentControl { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<relationship> relationship { get; set; }
        public virtual DbSet<roomChat> roomChat { get; set; }
        public virtual DbSet<statusGame> statusGame { get; set; }
        public virtual DbSet<statusRelationship> statusRelationship { get; set; }
        public virtual DbSet<timePlayed> timePlayed { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userGame> userGame { get; set; }
        public virtual DbSet<userRoomChat> userRoomChat { get; set; }
        public virtual DbSet<userLab> userLab { get; set; }
        public virtual DbSet<wallet> wallet { get; set; }
    }
}
