//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationBalance
    {
        public int idOperation { get; set; }
        public int idBalance { get; set; }
        public decimal operation { get; set; }
        public Nullable<System.DateTime> dateTimeOperation { get; set; }
    
        public virtual balance balance { get; set; }
    }
}
