//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Collections.Generic;
    
    public partial class parentControl
    {
        public int idParentControl { get; set; }
        public int idUserParent { get; set; }
        public int idUserChild { get; set; }
        public Nullable<System.TimeSpan> timeLimit { get; set; }
        public Nullable<bool> confirmed { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
