//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP11_3a
{
    using System;
    using System.Collections.Generic;
    
    public partial class userGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userGame()
        {
            this.timePlayed = new HashSet<timePlayed>();
        }
    
        public int idUserGame { get; set; }
        public int idGame { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> dateBuy { get; set; }
        public Nullable<decimal> priceBuy { get; set; }
        public Nullable<int> idStatusGame { get; set; }
    
        public virtual game game { get; set; }
        public virtual statusGame statusGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timePlayed> timePlayed { get; set; }
        public virtual user user { get; set; }
    }
}
